# Sed script to update image extensions to WebP
s|("/images/me\.jpg")|("/images/me\.webp")|g
s|("/images/me\.[jJ][pP][gG]")|("/images/me\.webp")|g
s|("/images/me\.[jJ][pP][eE][gG]")|("/images/me\.webp")|g
s|("/images/me\.[pP][nN][gG]")|("/images/me\.webp")|g
s|("/images/designing-a-festival/2015-theme\.jpg")|("/images/designing-a-festival/2015-theme\.webp")|g
s|("/images/designing-a-festival/2015-theme\.[jJ][pP][gG]")|("/images/designing-a-festival/2015-theme\.webp")|g
s|("/images/designing-a-festival/2015-theme\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2015-theme\.webp")|g
s|("/images/designing-a-festival/2015-theme\.[pP][nN][gG]")|("/images/designing-a-festival/2015-theme\.webp")|g
s|("/images/designing-a-festival/2019-subway\.jpeg")|("/images/designing-a-festival/2019-subway\.webp")|g
s|("/images/designing-a-festival/2019-subway\.[jJ][pP][gG]")|("/images/designing-a-festival/2019-subway\.webp")|g
s|("/images/designing-a-festival/2019-subway\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2019-subway\.webp")|g
s|("/images/designing-a-festival/2019-subway\.[pP][nN][gG]")|("/images/designing-a-festival/2019-subway\.webp")|g
s|("/images/designing-a-festival/2013-theme\.jpg")|("/images/designing-a-festival/2013-theme\.webp")|g
s|("/images/designing-a-festival/2013-theme\.[jJ][pP][gG]")|("/images/designing-a-festival/2013-theme\.webp")|g
s|("/images/designing-a-festival/2013-theme\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2013-theme\.webp")|g
s|("/images/designing-a-festival/2013-theme\.[pP][nN][gG]")|("/images/designing-a-festival/2013-theme\.webp")|g
s|("/images/designing-a-festival/2013-poster\.jpg")|("/images/designing-a-festival/2013-poster\.webp")|g
s|("/images/designing-a-festival/2013-poster\.[jJ][pP][gG]")|("/images/designing-a-festival/2013-poster\.webp")|g
s|("/images/designing-a-festival/2013-poster\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2013-poster\.webp")|g
s|("/images/designing-a-festival/2013-poster\.[pP][nN][gG]")|("/images/designing-a-festival/2013-poster\.webp")|g
s|("/images/designing-a-festival/banner\.jpg")|("/images/designing-a-festival/banner\.webp")|g
s|("/images/designing-a-festival/banner\.[jJ][pP][gG]")|("/images/designing-a-festival/banner\.webp")|g
s|("/images/designing-a-festival/banner\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/banner\.webp")|g
s|("/images/designing-a-festival/banner\.[pP][nN][gG]")|("/images/designing-a-festival/banner\.webp")|g
s|("/images/designing-a-festival/2011-logo\.jpg")|("/images/designing-a-festival/2011-logo\.webp")|g
s|("/images/designing-a-festival/2011-logo\.[jJ][pP][gG]")|("/images/designing-a-festival/2011-logo\.webp")|g
s|("/images/designing-a-festival/2011-logo\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2011-logo\.webp")|g
s|("/images/designing-a-festival/2011-logo\.[pP][nN][gG]")|("/images/designing-a-festival/2011-logo\.webp")|g
s|("/images/designing-a-festival/2019-ads2\.jpeg")|("/images/designing-a-festival/2019-ads2\.webp")|g
s|("/images/designing-a-festival/2019-ads2\.[jJ][pP][gG]")|("/images/designing-a-festival/2019-ads2\.webp")|g
s|("/images/designing-a-festival/2019-ads2\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2019-ads2\.webp")|g
s|("/images/designing-a-festival/2019-ads2\.[pP][nN][gG]")|("/images/designing-a-festival/2019-ads2\.webp")|g
s|("/images/designing-a-festival/2015-assets\.jpg")|("/images/designing-a-festival/2015-assets\.webp")|g
s|("/images/designing-a-festival/2015-assets\.[jJ][pP][gG]")|("/images/designing-a-festival/2015-assets\.webp")|g
s|("/images/designing-a-festival/2015-assets\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2015-assets\.webp")|g
s|("/images/designing-a-festival/2015-assets\.[pP][nN][gG]")|("/images/designing-a-festival/2015-assets\.webp")|g
s|("/images/designing-a-festival/2008-poster\.jpg")|("/images/designing-a-festival/2008-poster\.webp")|g
s|("/images/designing-a-festival/2008-poster\.[jJ][pP][gG]")|("/images/designing-a-festival/2008-poster\.webp")|g
s|("/images/designing-a-festival/2008-poster\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2008-poster\.webp")|g
s|("/images/designing-a-festival/2008-poster\.[pP][nN][gG]")|("/images/designing-a-festival/2008-poster\.webp")|g
s|("/images/designing-a-festival/2015-app\.jpg")|("/images/designing-a-festival/2015-app\.webp")|g
s|("/images/designing-a-festival/2015-app\.[jJ][pP][gG]")|("/images/designing-a-festival/2015-app\.webp")|g
s|("/images/designing-a-festival/2015-app\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2015-app\.webp")|g
s|("/images/designing-a-festival/2015-app\.[pP][nN][gG]")|("/images/designing-a-festival/2015-app\.webp")|g
s|("/images/designing-a-festival/2019-billboard\.png")|("/images/designing-a-festival/2019-billboard\.webp")|g
s|("/images/designing-a-festival/2019-billboard\.[jJ][pP][gG]")|("/images/designing-a-festival/2019-billboard\.webp")|g
s|("/images/designing-a-festival/2019-billboard\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2019-billboard\.webp")|g
s|("/images/designing-a-festival/2019-billboard\.[pP][nN][gG]")|("/images/designing-a-festival/2019-billboard\.webp")|g
s|("/images/designing-a-festival/2019-poster1\.png")|("/images/designing-a-festival/2019-poster1\.webp")|g
s|("/images/designing-a-festival/2019-poster1\.[jJ][pP][gG]")|("/images/designing-a-festival/2019-poster1\.webp")|g
s|("/images/designing-a-festival/2019-poster1\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2019-poster1\.webp")|g
s|("/images/designing-a-festival/2019-poster1\.[pP][nN][gG]")|("/images/designing-a-festival/2019-poster1\.webp")|g
s|("/images/designing-a-festival/2015-poster4\.jpg")|("/images/designing-a-festival/2015-poster4\.webp")|g
s|("/images/designing-a-festival/2015-poster4\.[jJ][pP][gG]")|("/images/designing-a-festival/2015-poster4\.webp")|g
s|("/images/designing-a-festival/2015-poster4\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2015-poster4\.webp")|g
s|("/images/designing-a-festival/2015-poster4\.[pP][nN][gG]")|("/images/designing-a-festival/2015-poster4\.webp")|g
s|("/images/designing-a-festival/2015-poster1\.jpg")|("/images/designing-a-festival/2015-poster1\.webp")|g
s|("/images/designing-a-festival/2015-poster1\.[jJ][pP][gG]")|("/images/designing-a-festival/2015-poster1\.webp")|g
s|("/images/designing-a-festival/2015-poster1\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2015-poster1\.webp")|g
s|("/images/designing-a-festival/2015-poster1\.[pP][nN][gG]")|("/images/designing-a-festival/2015-poster1\.webp")|g
s|("/images/designing-a-festival/2023-pitch\.png")|("/images/designing-a-festival/2023-pitch\.webp")|g
s|("/images/designing-a-festival/2023-pitch\.[jJ][pP][gG]")|("/images/designing-a-festival/2023-pitch\.webp")|g
s|("/images/designing-a-festival/2023-pitch\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2023-pitch\.webp")|g
s|("/images/designing-a-festival/2023-pitch\.[pP][nN][gG]")|("/images/designing-a-festival/2023-pitch\.webp")|g
s|("/images/designing-a-festival/2015-poster3\.jpg")|("/images/designing-a-festival/2015-poster3\.webp")|g
s|("/images/designing-a-festival/2015-poster3\.[jJ][pP][gG]")|("/images/designing-a-festival/2015-poster3\.webp")|g
s|("/images/designing-a-festival/2015-poster3\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2015-poster3\.webp")|g
s|("/images/designing-a-festival/2015-poster3\.[pP][nN][gG]")|("/images/designing-a-festival/2015-poster3\.webp")|g
s|("/images/designing-a-festival/2013-magazine\.jpg")|("/images/designing-a-festival/2013-magazine\.webp")|g
s|("/images/designing-a-festival/2013-magazine\.[jJ][pP][gG]")|("/images/designing-a-festival/2013-magazine\.webp")|g
s|("/images/designing-a-festival/2013-magazine\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2013-magazine\.webp")|g
s|("/images/designing-a-festival/2013-magazine\.[pP][nN][gG]")|("/images/designing-a-festival/2013-magazine\.webp")|g
s|("/images/designing-a-festival/2015-poster2\.jpg")|("/images/designing-a-festival/2015-poster2\.webp")|g
s|("/images/designing-a-festival/2015-poster2\.[jJ][pP][gG]")|("/images/designing-a-festival/2015-poster2\.webp")|g
s|("/images/designing-a-festival/2015-poster2\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2015-poster2\.webp")|g
s|("/images/designing-a-festival/2015-poster2\.[pP][nN][gG]")|("/images/designing-a-festival/2015-poster2\.webp")|g
s|("/images/designing-a-festival/2011-poster\.jpg")|("/images/designing-a-festival/2011-poster\.webp")|g
s|("/images/designing-a-festival/2011-poster\.[jJ][pP][gG]")|("/images/designing-a-festival/2011-poster\.webp")|g
s|("/images/designing-a-festival/2011-poster\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2011-poster\.webp")|g
s|("/images/designing-a-festival/2011-poster\.[pP][nN][gG]")|("/images/designing-a-festival/2011-poster\.webp")|g
s|("/images/designing-a-festival/2017-theme\.jpg")|("/images/designing-a-festival/2017-theme\.webp")|g
s|("/images/designing-a-festival/2017-theme\.[jJ][pP][gG]")|("/images/designing-a-festival/2017-theme\.webp")|g
s|("/images/designing-a-festival/2017-theme\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2017-theme\.webp")|g
s|("/images/designing-a-festival/2017-theme\.[pP][nN][gG]")|("/images/designing-a-festival/2017-theme\.webp")|g
s|("/images/designing-a-festival/2013-banners\.jpg")|("/images/designing-a-festival/2013-banners\.webp")|g
s|("/images/designing-a-festival/2013-banners\.[jJ][pP][gG]")|("/images/designing-a-festival/2013-banners\.webp")|g
s|("/images/designing-a-festival/2013-banners\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2013-banners\.webp")|g
s|("/images/designing-a-festival/2013-banners\.[pP][nN][gG]")|("/images/designing-a-festival/2013-banners\.webp")|g
s|("/images/designing-a-festival/2017-events\.jpg")|("/images/designing-a-festival/2017-events\.webp")|g
s|("/images/designing-a-festival/2017-events\.[jJ][pP][gG]")|("/images/designing-a-festival/2017-events\.webp")|g
s|("/images/designing-a-festival/2017-events\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2017-events\.webp")|g
s|("/images/designing-a-festival/2017-events\.[pP][nN][gG]")|("/images/designing-a-festival/2017-events\.webp")|g
s|("/images/designing-a-festival/2013-assets\.jpg")|("/images/designing-a-festival/2013-assets\.webp")|g
s|("/images/designing-a-festival/2013-assets\.[jJ][pP][gG]")|("/images/designing-a-festival/2013-assets\.webp")|g
s|("/images/designing-a-festival/2013-assets\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2013-assets\.webp")|g
s|("/images/designing-a-festival/2013-assets\.[pP][nN][gG]")|("/images/designing-a-festival/2013-assets\.webp")|g
s|("/images/designing-a-festival/2015-guidelines\.jpg")|("/images/designing-a-festival/2015-guidelines\.webp")|g
s|("/images/designing-a-festival/2015-guidelines\.[jJ][pP][gG]")|("/images/designing-a-festival/2015-guidelines\.webp")|g
s|("/images/designing-a-festival/2015-guidelines\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2015-guidelines\.webp")|g
s|("/images/designing-a-festival/2015-guidelines\.[pP][nN][gG]")|("/images/designing-a-festival/2015-guidelines\.webp")|g
s|("/images/designing-a-festival/2017-poster\.jpg")|("/images/designing-a-festival/2017-poster\.webp")|g
s|("/images/designing-a-festival/2017-poster\.[jJ][pP][gG]")|("/images/designing-a-festival/2017-poster\.webp")|g
s|("/images/designing-a-festival/2017-poster\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2017-poster\.webp")|g
s|("/images/designing-a-festival/2017-poster\.[pP][nN][gG]")|("/images/designing-a-festival/2017-poster\.webp")|g
s|("/images/designing-a-festival/2017-Nowruz\.jpg")|("/images/designing-a-festival/2017-Nowruz\.webp")|g
s|("/images/designing-a-festival/2017-Nowruz\.[jJ][pP][gG]")|("/images/designing-a-festival/2017-Nowruz\.webp")|g
s|("/images/designing-a-festival/2017-Nowruz\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2017-Nowruz\.webp")|g
s|("/images/designing-a-festival/2017-Nowruz\.[pP][nN][gG]")|("/images/designing-a-festival/2017-Nowruz\.webp")|g
s|("/images/designing-a-festival/2019-banner\.jpeg")|("/images/designing-a-festival/2019-banner\.webp")|g
s|("/images/designing-a-festival/2019-banner\.[jJ][pP][gG]")|("/images/designing-a-festival/2019-banner\.webp")|g
s|("/images/designing-a-festival/2019-banner\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2019-banner\.webp")|g
s|("/images/designing-a-festival/2019-banner\.[pP][nN][gG]")|("/images/designing-a-festival/2019-banner\.webp")|g
s|("/images/designing-a-festival/2017-poster2\.jpg")|("/images/designing-a-festival/2017-poster2\.webp")|g
s|("/images/designing-a-festival/2017-poster2\.[jJ][pP][gG]")|("/images/designing-a-festival/2017-poster2\.webp")|g
s|("/images/designing-a-festival/2017-poster2\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2017-poster2\.webp")|g
s|("/images/designing-a-festival/2017-poster2\.[pP][nN][gG]")|("/images/designing-a-festival/2017-poster2\.webp")|g
s|("/images/designing-a-festival/2011-guidelines\.jpg")|("/images/designing-a-festival/2011-guidelines\.webp")|g
s|("/images/designing-a-festival/2011-guidelines\.[jJ][pP][gG]")|("/images/designing-a-festival/2011-guidelines\.webp")|g
s|("/images/designing-a-festival/2011-guidelines\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2011-guidelines\.webp")|g
s|("/images/designing-a-festival/2011-guidelines\.[pP][nN][gG]")|("/images/designing-a-festival/2011-guidelines\.webp")|g
s|("/images/designing-a-festival/2013-ads\.jpg")|("/images/designing-a-festival/2013-ads\.webp")|g
s|("/images/designing-a-festival/2013-ads\.[jJ][pP][gG]")|("/images/designing-a-festival/2013-ads\.webp")|g
s|("/images/designing-a-festival/2013-ads\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2013-ads\.webp")|g
s|("/images/designing-a-festival/2013-ads\.[pP][nN][gG]")|("/images/designing-a-festival/2013-ads\.webp")|g
s|("/images/designing-a-festival/golobolbol\.jpg")|("/images/designing-a-festival/golobolbol\.webp")|g
s|("/images/designing-a-festival/golobolbol\.[jJ][pP][gG]")|("/images/designing-a-festival/golobolbol\.webp")|g
s|("/images/designing-a-festival/golobolbol\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/golobolbol\.webp")|g
s|("/images/designing-a-festival/golobolbol\.[pP][nN][gG]")|("/images/designing-a-festival/golobolbol\.webp")|g
s|("/images/designing-a-festival/2019-poster3\.jpeg")|("/images/designing-a-festival/2019-poster3\.webp")|g
s|("/images/designing-a-festival/2019-poster3\.[jJ][pP][gG]")|("/images/designing-a-festival/2019-poster3\.webp")|g
s|("/images/designing-a-festival/2019-poster3\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2019-poster3\.webp")|g
s|("/images/designing-a-festival/2019-poster3\.[pP][nN][gG]")|("/images/designing-a-festival/2019-poster3\.webp")|g
s|("/images/designing-a-festival/2008-logo\.jpg")|("/images/designing-a-festival/2008-logo\.webp")|g
s|("/images/designing-a-festival/2008-logo\.[jJ][pP][gG]")|("/images/designing-a-festival/2008-logo\.webp")|g
s|("/images/designing-a-festival/2008-logo\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2008-logo\.webp")|g
s|("/images/designing-a-festival/2008-logo\.[pP][nN][gG]")|("/images/designing-a-festival/2008-logo\.webp")|g
s|("/images/designing-a-festival/2013-app\.jpg")|("/images/designing-a-festival/2013-app\.webp")|g
s|("/images/designing-a-festival/2013-app\.[jJ][pP][gG]")|("/images/designing-a-festival/2013-app\.webp")|g
s|("/images/designing-a-festival/2013-app\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2013-app\.webp")|g
s|("/images/designing-a-festival/2013-app\.[pP][nN][gG]")|("/images/designing-a-festival/2013-app\.webp")|g
s|("/images/designing-a-festival/2017-guidelines\.jpg")|("/images/designing-a-festival/2017-guidelines\.webp")|g
s|("/images/designing-a-festival/2017-guidelines\.[jJ][pP][gG]")|("/images/designing-a-festival/2017-guidelines\.webp")|g
s|("/images/designing-a-festival/2017-guidelines\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2017-guidelines\.webp")|g
s|("/images/designing-a-festival/2017-guidelines\.[pP][nN][gG]")|("/images/designing-a-festival/2017-guidelines\.webp")|g
s|("/images/designing-a-festival/2019-poster2\.jpeg")|("/images/designing-a-festival/2019-poster2\.webp")|g
s|("/images/designing-a-festival/2019-poster2\.[jJ][pP][gG]")|("/images/designing-a-festival/2019-poster2\.webp")|g
s|("/images/designing-a-festival/2019-poster2\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2019-poster2\.webp")|g
s|("/images/designing-a-festival/2019-poster2\.[pP][nN][gG]")|("/images/designing-a-festival/2019-poster2\.webp")|g
s|("/images/designing-a-festival/2023-poster1\.jpg")|("/images/designing-a-festival/2023-poster1\.webp")|g
s|("/images/designing-a-festival/2023-poster1\.[jJ][pP][gG]")|("/images/designing-a-festival/2023-poster1\.webp")|g
s|("/images/designing-a-festival/2023-poster1\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2023-poster1\.webp")|g
s|("/images/designing-a-festival/2023-poster1\.[pP][nN][gG]")|("/images/designing-a-festival/2023-poster1\.webp")|g
s|("/images/designing-a-festival/2023-poster3\.jpg")|("/images/designing-a-festival/2023-poster3\.webp")|g
s|("/images/designing-a-festival/2023-poster3\.[jJ][pP][gG]")|("/images/designing-a-festival/2023-poster3\.webp")|g
s|("/images/designing-a-festival/2023-poster3\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2023-poster3\.webp")|g
s|("/images/designing-a-festival/2023-poster3\.[pP][nN][gG]")|("/images/designing-a-festival/2023-poster3\.webp")|g
s|("/images/designing-a-festival/2023-hero\.png")|("/images/designing-a-festival/2023-hero\.webp")|g
s|("/images/designing-a-festival/2023-hero\.[jJ][pP][gG]")|("/images/designing-a-festival/2023-hero\.webp")|g
s|("/images/designing-a-festival/2023-hero\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2023-hero\.webp")|g
s|("/images/designing-a-festival/2023-hero\.[pP][nN][gG]")|("/images/designing-a-festival/2023-hero\.webp")|g
s|("/images/designing-a-festival/2011-flyers\.jpg")|("/images/designing-a-festival/2011-flyers\.webp")|g
s|("/images/designing-a-festival/2011-flyers\.[jJ][pP][gG]")|("/images/designing-a-festival/2011-flyers\.webp")|g
s|("/images/designing-a-festival/2011-flyers\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2011-flyers\.webp")|g
s|("/images/designing-a-festival/2011-flyers\.[pP][nN][gG]")|("/images/designing-a-festival/2011-flyers\.webp")|g
s|("/images/designing-a-festival/2019-pitch\.png")|("/images/designing-a-festival/2019-pitch\.webp")|g
s|("/images/designing-a-festival/2019-pitch\.[jJ][pP][gG]")|("/images/designing-a-festival/2019-pitch\.webp")|g
s|("/images/designing-a-festival/2019-pitch\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2019-pitch\.webp")|g
s|("/images/designing-a-festival/2019-pitch\.[pP][nN][gG]")|("/images/designing-a-festival/2019-pitch\.webp")|g
s|("/images/designing-a-festival/2023-poster2\.jpg")|("/images/designing-a-festival/2023-poster2\.webp")|g
s|("/images/designing-a-festival/2023-poster2\.[jJ][pP][gG]")|("/images/designing-a-festival/2023-poster2\.webp")|g
s|("/images/designing-a-festival/2023-poster2\.[jJ][pP][eE][gG]")|("/images/designing-a-festival/2023-poster2\.webp")|g
s|("/images/designing-a-festival/2023-poster2\.[pP][nN][gG]")|("/images/designing-a-festival/2023-poster2\.webp")|g
s|("/images/scrolling-in-money/before\.png")|("/images/scrolling-in-money/before\.webp")|g
s|("/images/scrolling-in-money/before\.[jJ][pP][gG]")|("/images/scrolling-in-money/before\.webp")|g
s|("/images/scrolling-in-money/before\.[jJ][pP][eE][gG]")|("/images/scrolling-in-money/before\.webp")|g
s|("/images/scrolling-in-money/before\.[pP][nN][gG]")|("/images/scrolling-in-money/before\.webp")|g
s|("/images/scrolling-in-money/new-ads\.png")|("/images/scrolling-in-money/new-ads\.webp")|g
s|("/images/scrolling-in-money/new-ads\.[jJ][pP][gG]")|("/images/scrolling-in-money/new-ads\.webp")|g
s|("/images/scrolling-in-money/new-ads\.[jJ][pP][eE][gG]")|("/images/scrolling-in-money/new-ads\.webp")|g
s|("/images/scrolling-in-money/new-ads\.[pP][nN][gG]")|("/images/scrolling-in-money/new-ads\.webp")|g
s|("/images/scrolling-in-money/rich-text-ads\.png")|("/images/scrolling-in-money/rich-text-ads\.webp")|g
s|("/images/scrolling-in-money/rich-text-ads\.[jJ][pP][gG]")|("/images/scrolling-in-money/rich-text-ads\.webp")|g
s|("/images/scrolling-in-money/rich-text-ads\.[jJ][pP][eE][gG]")|("/images/scrolling-in-money/rich-text-ads\.webp")|g
s|("/images/scrolling-in-money/rich-text-ads\.[pP][nN][gG]")|("/images/scrolling-in-money/rich-text-ads\.webp")|g
s|("/images/scrolling-in-money/rich-ads\.png")|("/images/scrolling-in-money/rich-ads\.webp")|g
s|("/images/scrolling-in-money/rich-ads\.[jJ][pP][gG]")|("/images/scrolling-in-money/rich-ads\.webp")|g
s|("/images/scrolling-in-money/rich-ads\.[jJ][pP][eE][gG]")|("/images/scrolling-in-money/rich-ads\.webp")|g
s|("/images/scrolling-in-money/rich-ads\.[pP][nN][gG]")|("/images/scrolling-in-money/rich-ads\.webp")|g
s|("/images/scrolling-in-money/wireframes\.png")|("/images/scrolling-in-money/wireframes\.webp")|g
s|("/images/scrolling-in-money/wireframes\.[jJ][pP][gG]")|("/images/scrolling-in-money/wireframes\.webp")|g
s|("/images/scrolling-in-money/wireframes\.[jJ][pP][eE][gG]")|("/images/scrolling-in-money/wireframes\.webp")|g
s|("/images/scrolling-in-money/wireframes\.[pP][nN][gG]")|("/images/scrolling-in-money/wireframes\.webp")|g
s|("/images/scrolling-in-money/campaign-before\.png")|("/images/scrolling-in-money/campaign-before\.webp")|g
s|("/images/scrolling-in-money/campaign-before\.[jJ][pP][gG]")|("/images/scrolling-in-money/campaign-before\.webp")|g
s|("/images/scrolling-in-money/campaign-before\.[jJ][pP][eE][gG]")|("/images/scrolling-in-money/campaign-before\.webp")|g
s|("/images/scrolling-in-money/campaign-before\.[pP][nN][gG]")|("/images/scrolling-in-money/campaign-before\.webp")|g
s|("/images/scrolling-in-money/cards\.png")|("/images/scrolling-in-money/cards\.webp")|g
s|("/images/scrolling-in-money/cards\.[jJ][pP][gG]")|("/images/scrolling-in-money/cards\.webp")|g
s|("/images/scrolling-in-money/cards\.[jJ][pP][eE][gG]")|("/images/scrolling-in-money/cards\.webp")|g
s|("/images/scrolling-in-money/cards\.[pP][nN][gG]")|("/images/scrolling-in-money/cards\.webp")|g
s|("/images/scrolling-in-money/stepper\.png")|("/images/scrolling-in-money/stepper\.webp")|g
s|("/images/scrolling-in-money/stepper\.[jJ][pP][gG]")|("/images/scrolling-in-money/stepper\.webp")|g
s|("/images/scrolling-in-money/stepper\.[jJ][pP][eE][gG]")|("/images/scrolling-in-money/stepper\.webp")|g
s|("/images/scrolling-in-money/stepper\.[pP][nN][gG]")|("/images/scrolling-in-money/stepper\.webp")|g
s|("/images/scrolling-in-money/summary-final\.png")|("/images/scrolling-in-money/summary-final\.webp")|g
s|("/images/scrolling-in-money/summary-final\.[jJ][pP][gG]")|("/images/scrolling-in-money/summary-final\.webp")|g
s|("/images/scrolling-in-money/summary-final\.[jJ][pP][eE][gG]")|("/images/scrolling-in-money/summary-final\.webp")|g
s|("/images/scrolling-in-money/summary-final\.[pP][nN][gG]")|("/images/scrolling-in-money/summary-final\.webp")|g
s|("/images/scrolling-in-money/campaign-explorations\.png")|("/images/scrolling-in-money/campaign-explorations\.webp")|g
s|("/images/scrolling-in-money/campaign-explorations\.[jJ][pP][gG]")|("/images/scrolling-in-money/campaign-explorations\.webp")|g
s|("/images/scrolling-in-money/campaign-explorations\.[jJ][pP][eE][gG]")|("/images/scrolling-in-money/campaign-explorations\.webp")|g
s|("/images/scrolling-in-money/campaign-explorations\.[pP][nN][gG]")|("/images/scrolling-in-money/campaign-explorations\.webp")|g
s|("/images/project1\.jpg")|("/images/project1\.webp")|g
s|("/images/project1\.[jJ][pP][gG]")|("/images/project1\.webp")|g
s|("/images/project1\.[jJ][pP][eE][gG]")|("/images/project1\.webp")|g
s|("/images/project1\.[pP][nN][gG]")|("/images/project1\.webp")|g
s|("/images/talking-to-strangers/offline-stats\.jpg")|("/images/talking-to-strangers/offline-stats\.webp")|g
s|("/images/talking-to-strangers/offline-stats\.[jJ][pP][gG]")|("/images/talking-to-strangers/offline-stats\.webp")|g
s|("/images/talking-to-strangers/offline-stats\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/offline-stats\.webp")|g
s|("/images/talking-to-strangers/offline-stats\.[pP][nN][gG]")|("/images/talking-to-strangers/offline-stats\.webp")|g
s|("/images/talking-to-strangers/uxr\.png")|("/images/talking-to-strangers/uxr\.webp")|g
s|("/images/talking-to-strangers/uxr\.[jJ][pP][gG]")|("/images/talking-to-strangers/uxr\.webp")|g
s|("/images/talking-to-strangers/uxr\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/uxr\.webp")|g
s|("/images/talking-to-strangers/uxr\.[pP][nN][gG]")|("/images/talking-to-strangers/uxr\.webp")|g
s|("/images/talking-to-strangers/roadmap\.png")|("/images/talking-to-strangers/roadmap\.webp")|g
s|("/images/talking-to-strangers/roadmap\.[jJ][pP][gG]")|("/images/talking-to-strangers/roadmap\.webp")|g
s|("/images/talking-to-strangers/roadmap\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/roadmap\.webp")|g
s|("/images/talking-to-strangers/roadmap\.[pP][nN][gG]")|("/images/talking-to-strangers/roadmap\.webp")|g
s|("/images/talking-to-strangers/t2t-process\.png")|("/images/talking-to-strangers/t2t-process\.webp")|g
s|("/images/talking-to-strangers/t2t-process\.[jJ][pP][gG]")|("/images/talking-to-strangers/t2t-process\.webp")|g
s|("/images/talking-to-strangers/t2t-process\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/t2t-process\.webp")|g
s|("/images/talking-to-strangers/t2t-process\.[pP][nN][gG]")|("/images/talking-to-strangers/t2t-process\.webp")|g
s|("/images/talking-to-strangers/offline-problem\.jpg")|("/images/talking-to-strangers/offline-problem\.webp")|g
s|("/images/talking-to-strangers/offline-problem\.[jJ][pP][gG]")|("/images/talking-to-strangers/offline-problem\.webp")|g
s|("/images/talking-to-strangers/offline-problem\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/offline-problem\.webp")|g
s|("/images/talking-to-strangers/offline-problem\.[pP][nN][gG]")|("/images/talking-to-strangers/offline-problem\.webp")|g
s|("/images/talking-to-strangers/what-we-tested\.jpg")|("/images/talking-to-strangers/what-we-tested\.webp")|g
s|("/images/talking-to-strangers/what-we-tested\.[jJ][pP][gG]")|("/images/talking-to-strangers/what-we-tested\.webp")|g
s|("/images/talking-to-strangers/what-we-tested\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/what-we-tested\.webp")|g
s|("/images/talking-to-strangers/what-we-tested\.[pP][nN][gG]")|("/images/talking-to-strangers/what-we-tested\.webp")|g
s|("/images/talking-to-strangers/offsite\.jpg")|("/images/talking-to-strangers/offsite\.webp")|g
s|("/images/talking-to-strangers/offsite\.[jJ][pP][gG]")|("/images/talking-to-strangers/offsite\.webp")|g
s|("/images/talking-to-strangers/offsite\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/offsite\.webp")|g
s|("/images/talking-to-strangers/offsite\.[pP][nN][gG]")|("/images/talking-to-strangers/offsite\.webp")|g
s|("/images/talking-to-strangers/contextual-promo\.jpg")|("/images/talking-to-strangers/contextual-promo\.webp")|g
s|("/images/talking-to-strangers/contextual-promo\.[jJ][pP][gG]")|("/images/talking-to-strangers/contextual-promo\.webp")|g
s|("/images/talking-to-strangers/contextual-promo\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/contextual-promo\.webp")|g
s|("/images/talking-to-strangers/contextual-promo\.[pP][nN][gG]")|("/images/talking-to-strangers/contextual-promo\.webp")|g
s|("/images/talking-to-strangers/tap-to-translate\.png")|("/images/talking-to-strangers/tap-to-translate\.webp")|g
s|("/images/talking-to-strangers/tap-to-translate\.[jJ][pP][gG]")|("/images/talking-to-strangers/tap-to-translate\.webp")|g
s|("/images/talking-to-strangers/tap-to-translate\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/tap-to-translate\.webp")|g
s|("/images/talking-to-strangers/tap-to-translate\.[pP][nN][gG]")|("/images/talking-to-strangers/tap-to-translate\.webp")|g
s|("/images/talking-to-strangers/offline-testing\.jpg")|("/images/talking-to-strangers/offline-testing\.webp")|g
s|("/images/talking-to-strangers/offline-testing\.[jJ][pP][gG]")|("/images/talking-to-strangers/offline-testing\.webp")|g
s|("/images/talking-to-strangers/offline-testing\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/offline-testing\.webp")|g
s|("/images/talking-to-strangers/offline-testing\.[pP][nN][gG]")|("/images/talking-to-strangers/offline-testing\.webp")|g
s|("/images/talking-to-strangers/designsystem\.png")|("/images/talking-to-strangers/designsystem\.webp")|g
s|("/images/talking-to-strangers/designsystem\.[jJ][pP][gG]")|("/images/talking-to-strangers/designsystem\.webp")|g
s|("/images/talking-to-strangers/designsystem\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/designsystem\.webp")|g
s|("/images/talking-to-strangers/designsystem\.[pP][nN][gG]")|("/images/talking-to-strangers/designsystem\.webp")|g
s|("/images/talking-to-strangers/foundations\.png")|("/images/talking-to-strangers/foundations\.webp")|g
s|("/images/talking-to-strangers/foundations\.[jJ][pP][gG]")|("/images/talking-to-strangers/foundations\.webp")|g
s|("/images/talking-to-strangers/foundations\.[jJ][pP][eE][gG]")|("/images/talking-to-strangers/foundations\.webp")|g
s|("/images/talking-to-strangers/foundations\.[pP][nN][gG]")|("/images/talking-to-strangers/foundations\.webp")|g
s|("/images/the-arsenal-of-startups/emails-mobile\.png")|("/images/the-arsenal-of-startups/emails-mobile\.webp")|g
s|("/images/the-arsenal-of-startups/emails-mobile\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/emails-mobile\.webp")|g
s|("/images/the-arsenal-of-startups/emails-mobile\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/emails-mobile\.webp")|g
s|("/images/the-arsenal-of-startups/emails-mobile\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/emails-mobile\.webp")|g
s|("/images/the-arsenal-of-startups/code\.png")|("/images/the-arsenal-of-startups/code\.webp")|g
s|("/images/the-arsenal-of-startups/code\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/code\.webp")|g
s|("/images/the-arsenal-of-startups/code\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/code\.webp")|g
s|("/images/the-arsenal-of-startups/code\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/code\.webp")|g
s|("/images/the-arsenal-of-startups/other-landing-pages\.png")|("/images/the-arsenal-of-startups/other-landing-pages\.webp")|g
s|("/images/the-arsenal-of-startups/other-landing-pages\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/other-landing-pages\.webp")|g
s|("/images/the-arsenal-of-startups/other-landing-pages\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/other-landing-pages\.webp")|g
s|("/images/the-arsenal-of-startups/other-landing-pages\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/other-landing-pages\.webp")|g
s|("/images/the-arsenal-of-startups/tweets\.png")|("/images/the-arsenal-of-startups/tweets\.webp")|g
s|("/images/the-arsenal-of-startups/tweets\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/tweets\.webp")|g
s|("/images/the-arsenal-of-startups/tweets\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/tweets\.webp")|g
s|("/images/the-arsenal-of-startups/tweets\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/tweets\.webp")|g
s|("/images/the-arsenal-of-startups/landing-page-checker\.png")|("/images/the-arsenal-of-startups/landing-page-checker\.webp")|g
s|("/images/the-arsenal-of-startups/landing-page-checker\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/landing-page-checker\.webp")|g
s|("/images/the-arsenal-of-startups/landing-page-checker\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/landing-page-checker\.webp")|g
s|("/images/the-arsenal-of-startups/landing-page-checker\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/landing-page-checker\.webp")|g
s|("/images/the-arsenal-of-startups/main-landing-page\.png")|("/images/the-arsenal-of-startups/main-landing-page\.webp")|g
s|("/images/the-arsenal-of-startups/main-landing-page\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/main-landing-page\.webp")|g
s|("/images/the-arsenal-of-startups/main-landing-page\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/main-landing-page\.webp")|g
s|("/images/the-arsenal-of-startups/main-landing-page\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/main-landing-page\.webp")|g
s|("/images/the-arsenal-of-startups/landing-pages\.png")|("/images/the-arsenal-of-startups/landing-pages\.webp")|g
s|("/images/the-arsenal-of-startups/landing-pages\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/landing-pages\.webp")|g
s|("/images/the-arsenal-of-startups/landing-pages\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/landing-pages\.webp")|g
s|("/images/the-arsenal-of-startups/landing-pages\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/landing-pages\.webp")|g
s|("/images/the-arsenal-of-startups/blog\.png")|("/images/the-arsenal-of-startups/blog\.webp")|g
s|("/images/the-arsenal-of-startups/blog\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/blog\.webp")|g
s|("/images/the-arsenal-of-startups/blog\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/blog\.webp")|g
s|("/images/the-arsenal-of-startups/blog\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/blog\.webp")|g
s|("/images/the-arsenal-of-startups/gift\.jpg")|("/images/the-arsenal-of-startups/gift\.webp")|g
s|("/images/the-arsenal-of-startups/gift\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/gift\.webp")|g
s|("/images/the-arsenal-of-startups/gift\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/gift\.webp")|g
s|("/images/the-arsenal-of-startups/gift\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/gift\.webp")|g
s|("/images/the-arsenal-of-startups/analytics\.png")|("/images/the-arsenal-of-startups/analytics\.webp")|g
s|("/images/the-arsenal-of-startups/analytics\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/analytics\.webp")|g
s|("/images/the-arsenal-of-startups/analytics\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/analytics\.webp")|g
s|("/images/the-arsenal-of-startups/analytics\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/analytics\.webp")|g
s|("/images/the-arsenal-of-startups/landing-pages2\.png")|("/images/the-arsenal-of-startups/landing-pages2\.webp")|g
s|("/images/the-arsenal-of-startups/landing-pages2\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/landing-pages2\.webp")|g
s|("/images/the-arsenal-of-startups/landing-pages2\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/landing-pages2\.webp")|g
s|("/images/the-arsenal-of-startups/landing-pages2\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/landing-pages2\.webp")|g
s|("/images/the-arsenal-of-startups/litmus-wireframes\.png")|("/images/the-arsenal-of-startups/litmus-wireframes\.webp")|g
s|("/images/the-arsenal-of-startups/litmus-wireframes\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/litmus-wireframes\.webp")|g
s|("/images/the-arsenal-of-startups/litmus-wireframes\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/litmus-wireframes\.webp")|g
s|("/images/the-arsenal-of-startups/litmus-wireframes\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/litmus-wireframes\.webp")|g
s|("/images/the-arsenal-of-startups/emails\.png")|("/images/the-arsenal-of-startups/emails\.webp")|g
s|("/images/the-arsenal-of-startups/emails\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/emails\.webp")|g
s|("/images/the-arsenal-of-startups/emails\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/emails\.webp")|g
s|("/images/the-arsenal-of-startups/emails\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/emails\.webp")|g
s|("/images/the-arsenal-of-startups/all-screens\.png")|("/images/the-arsenal-of-startups/all-screens\.webp")|g
s|("/images/the-arsenal-of-startups/all-screens\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/all-screens\.webp")|g
s|("/images/the-arsenal-of-startups/all-screens\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/all-screens\.webp")|g
s|("/images/the-arsenal-of-startups/all-screens\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/all-screens\.webp")|g
s|("/images/the-arsenal-of-startups/billing\.png")|("/images/the-arsenal-of-startups/billing\.webp")|g
s|("/images/the-arsenal-of-startups/billing\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/billing\.webp")|g
s|("/images/the-arsenal-of-startups/billing\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/billing\.webp")|g
s|("/images/the-arsenal-of-startups/billing\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/billing\.webp")|g
s|("/images/the-arsenal-of-startups/blog2\.png")|("/images/the-arsenal-of-startups/blog2\.webp")|g
s|("/images/the-arsenal-of-startups/blog2\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/blog2\.webp")|g
s|("/images/the-arsenal-of-startups/blog2\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/blog2\.webp")|g
s|("/images/the-arsenal-of-startups/blog2\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/blog2\.webp")|g
s|("/images/the-arsenal-of-startups/desktop1\.png")|("/images/the-arsenal-of-startups/desktop1\.webp")|g
s|("/images/the-arsenal-of-startups/desktop1\.[jJ][pP][gG]")|("/images/the-arsenal-of-startups/desktop1\.webp")|g
s|("/images/the-arsenal-of-startups/desktop1\.[jJ][pP][eE][gG]")|("/images/the-arsenal-of-startups/desktop1\.webp")|g
s|("/images/the-arsenal-of-startups/desktop1\.[pP][nN][gG]")|("/images/the-arsenal-of-startups/desktop1\.webp")|g
s|("/images/fish-in-your-ear/what-users-saw\.png")|("/images/fish-in-your-ear/what-users-saw\.webp")|g
s|("/images/fish-in-your-ear/what-users-saw\.[jJ][pP][gG]")|("/images/fish-in-your-ear/what-users-saw\.webp")|g
s|("/images/fish-in-your-ear/what-users-saw\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/what-users-saw\.webp")|g
s|("/images/fish-in-your-ear/what-users-saw\.[pP][nN][gG]")|("/images/fish-in-your-ear/what-users-saw\.webp")|g
s|("/images/fish-in-your-ear/first-designs\.png")|("/images/fish-in-your-ear/first-designs\.webp")|g
s|("/images/fish-in-your-ear/first-designs\.[jJ][pP][gG]")|("/images/fish-in-your-ear/first-designs\.webp")|g
s|("/images/fish-in-your-ear/first-designs\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/first-designs\.webp")|g
s|("/images/fish-in-your-ear/first-designs\.[pP][nN][gG]")|("/images/fish-in-your-ear/first-designs\.webp")|g
s|("/images/fish-in-your-ear/chart\.png")|("/images/fish-in-your-ear/chart\.webp")|g
s|("/images/fish-in-your-ear/chart\.[jJ][pP][gG]")|("/images/fish-in-your-ear/chart\.webp")|g
s|("/images/fish-in-your-ear/chart\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/chart\.webp")|g
s|("/images/fish-in-your-ear/chart\.[pP][nN][gG]")|("/images/fish-in-your-ear/chart\.webp")|g
s|("/images/fish-in-your-ear/quotes\.png")|("/images/fish-in-your-ear/quotes\.webp")|g
s|("/images/fish-in-your-ear/quotes\.[jJ][pP][gG]")|("/images/fish-in-your-ear/quotes\.webp")|g
s|("/images/fish-in-your-ear/quotes\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/quotes\.webp")|g
s|("/images/fish-in-your-ear/quotes\.[pP][nN][gG]")|("/images/fish-in-your-ear/quotes\.webp")|g
s|("/images/fish-in-your-ear/hypothesis\.png")|("/images/fish-in-your-ear/hypothesis\.webp")|g
s|("/images/fish-in-your-ear/hypothesis\.[jJ][pP][gG]")|("/images/fish-in-your-ear/hypothesis\.webp")|g
s|("/images/fish-in-your-ear/hypothesis\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/hypothesis\.webp")|g
s|("/images/fish-in-your-ear/hypothesis\.[pP][nN][gG]")|("/images/fish-in-your-ear/hypothesis\.webp")|g
s|("/images/fish-in-your-ear/twitter\.png")|("/images/fish-in-your-ear/twitter\.webp")|g
s|("/images/fish-in-your-ear/twitter\.[jJ][pP][gG]")|("/images/fish-in-your-ear/twitter\.webp")|g
s|("/images/fish-in-your-ear/twitter\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/twitter\.webp")|g
s|("/images/fish-in-your-ear/twitter\.[pP][nN][gG]")|("/images/fish-in-your-ear/twitter\.webp")|g
s|("/images/fish-in-your-ear/conversation\.png")|("/images/fish-in-your-ear/conversation\.webp")|g
s|("/images/fish-in-your-ear/conversation\.[jJ][pP][gG]")|("/images/fish-in-your-ear/conversation\.webp")|g
s|("/images/fish-in-your-ear/conversation\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/conversation\.webp")|g
s|("/images/fish-in-your-ear/conversation\.[pP][nN][gG]")|("/images/fish-in-your-ear/conversation\.webp")|g
s|("/images/fish-in-your-ear/take2\.png")|("/images/fish-in-your-ear/take2\.webp")|g
s|("/images/fish-in-your-ear/take2\.[jJ][pP][gG]")|("/images/fish-in-your-ear/take2\.webp")|g
s|("/images/fish-in-your-ear/take2\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/take2\.webp")|g
s|("/images/fish-in-your-ear/take2\.[pP][nN][gG]")|("/images/fish-in-your-ear/take2\.webp")|g
s|("/images/fish-in-your-ear/buds\.png")|("/images/fish-in-your-ear/buds\.webp")|g
s|("/images/fish-in-your-ear/buds\.[jJ][pP][gG]")|("/images/fish-in-your-ear/buds\.webp")|g
s|("/images/fish-in-your-ear/buds\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/buds\.webp")|g
s|("/images/fish-in-your-ear/buds\.[pP][nN][gG]")|("/images/fish-in-your-ear/buds\.webp")|g
s|("/images/fish-in-your-ear/icebreaker\.png")|("/images/fish-in-your-ear/icebreaker\.webp")|g
s|("/images/fish-in-your-ear/icebreaker\.[jJ][pP][gG]")|("/images/fish-in-your-ear/icebreaker\.webp")|g
s|("/images/fish-in-your-ear/icebreaker\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/icebreaker\.webp")|g
s|("/images/fish-in-your-ear/icebreaker\.[pP][nN][gG]")|("/images/fish-in-your-ear/icebreaker\.webp")|g
s|("/images/fish-in-your-ear/solution\.png")|("/images/fish-in-your-ear/solution\.webp")|g
s|("/images/fish-in-your-ear/solution\.[jJ][pP][gG]")|("/images/fish-in-your-ear/solution\.webp")|g
s|("/images/fish-in-your-ear/solution\.[jJ][pP][eE][gG]")|("/images/fish-in-your-ear/solution\.webp")|g
s|("/images/fish-in-your-ear/solution\.[pP][nN][gG]")|("/images/fish-in-your-ear/solution\.webp")|g
